name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - name: test
        env:
          RC_WP_CLIENT_ID: ${{ secrets.RC_WP_CLIENT_ID }}
          RC_WP_CLIENT_SECRET: ${{ secrets.RC_WP_CLIENT_SECRET }}
          RC_WP_SERVER: ${{ secrets.RC_WP_SERVER }}
          RC_WP_CALLER_JWT_TOKEN: ${{ secrets.RC_WP_CALLER_JWT_TOKEN }}
          RC_WP_RECEIVER_JWT_TOKEN: ${{ secrets.RC_WP_RECEIVER_JWT_TOKEN }}
        run: |
          yarn test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .coverage/lcov.info
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Release
        if: ${{ env.TAG != '' && github.repository == 'ringcentral/ringcentral-web-phone' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: ringcentral/ringcentral-web-phone
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
        if: ${{ env.TAG != '' && github.repository == 'ringcentral/ringcentral-web-phone' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
